export const workers = [
  {
    id: "1",
    username: "11",
    name: "Aarsh",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "2",
    username: "12",
    name: "Rishav",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "3",
    username: "13",
    name: "Ritik",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "4",
    username: "14",
    name: "Parth",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "5",
    username: "15",
    name: "Nityansh",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "6",
    username: "16",
    name: "Mayank",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "7",
    username: "17",
    name: "Aayan",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "8",
    username: "18",
    name: "Ariyan",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "9",
    username: "19",
    name: "Tushar",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "10",
    username: "20",
    name: "Gaurav",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "11",
    username: "21",
    name: "Piyush",
    age: 23,
    rating: "4.5",
    score: 10,
    img: "https://yt3.googleusercontent.com/ytc/APkrFKYyucaAqAGHZFcg6K-Eo90-SCfDXV2Hb3viu6tX=s900-c-k-c0x00ffffff-no-rj",
  },
];
